sudo: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
- 4.3
- stable
before_install:
- npm i -g npm
script:
- npm t
after_success: travis-after-all && npm run semantic-release
env:
  global:
  - secure: li2HT2tPRFVUsVytGSCQl1kkdukTWoKzwEWHsY7tm1Yp4WyajbP83t3X6R2tVizMudwFedjb6hHLdKIK0vxAa3QSa5dABtbhzQ/NOqpFJx6NfQkIYqeRnVCFbm/LItIFpsBW0IdwcNuWq46wMDixSvHzu4a9wUAKTJNcB/H2lTzdkjPM0ZS7ilbUxPpbAEcTKTMaAw8xJ2SUA/O0JQmZwd+Z7WTP9YWamDm0yNIz9rRx9c3IN9pXTK8HZAZ4DtkFAw4oE/6KUkS6jk8JTT0Ym32Z2R++Hw3bn1Tuco6Q6oku9/WxGTkuUCXR7JooRHmmnFsjZJnqYuZr31gB0sMQHAdnmg1Xbk4kWFKVBkZvo7jIaPzLkUf6MIXZUGbL5YDXaXzgMwAuNMuIShs/ftY2+JIqumpjaBWicEQaebaEO9N1Q5x6sLGI/YfOJ+Iiu28t8EUPzmdKGnL99VMrG/R3+3+8wNb6voqyJ1b0096M6MXfzqHrQLM826QKuDdxxmaXaMqSjJ3Ao2xAROdLKxK/Jz4eNJToUN6zx7Z3hB2FxQREK4nHMM7YvwGiya3NyanI6njK/eWHaJkZVaEjfz0jfLvoSc/lIc4i4HhvBVHVKHWMev+RIvlVvL+Ih5sZz8s9xSsp3ZpGilsfj98MsTIKIpOzSeW/44zDUHOMQXrfcq8=
  - secure: MoLDzo4p2GQYPFpwLXZYcXYNTs0ZJne0vTWaw4+j/61BUeTBVKt35eU4/a+ULNOWHHHrWLShT/ZlkOhs+a26+Wi2a4l3vI2ubh8hynlGEj5WUjabyfT2sLvlMo8b/2yjoRz9RVQRSoo6aQP+JnGNOku6/PJm2IRqCugoJVxvZ0r/z3YbIEhBSl/bFUQC16ZKRnIiPfOS7xFnDArF3JOlGAclbZoBvqvezmMXlSUkGswuAZRJP/Bdwgh6F0c/QswipmRiyDCIt4rsx5B8II3l/Pl+DJYG7DOaCjpcKV7ZikLB7sICJ7Mo4vt0K1YZhiRAknz9batsuARR+TWkMNpw9RnDvdfpnfGWQpXe2Oz9Y3eA9I9htBSnnJTpnT0HScvXdAf7aXVssGtIiQdHrMATy1RdrXH0M9Z8gXmikiZoVVGpyOKBKiX9DSa+SHNym5ej5rnqSJQmiRE52vGYTTNqAFvWF/XxYb0Adh3HcYKrIBElbB2l4B+RaDAD22+da1xVORzbL+7FoO1KFmWQwpkOfXSB3FbCUPzmKOezl8M/s5l6fL6XINVpJBaif8g4BTrrBq6loDYxZpEaOVWhwyc1Ffq24QWYF4LucO7LQUaK0BCe0+83KMFTzNF6hm7O1Z1uF0MpqLvFqnpCOqj+By/RMHhg6pWSKYsH0MnJytqSGgs=
