sudo: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
- 4.3
- stable
before_install:
- npm i -g npm
script:
- npm t
after_success: travis-after-all && npm run semantic-release
env:
  global:
  - secure: Q45dhaXaQuJxfZsaT4YZK2DUn7LZmdqR/wKVmJhZHyZAgU0Kgg54vUXtRp+ry9ncPJEGEImMQ+idPjoknZJBz8n9mUorS+4hxvrYLeNq2A86olQTAHs4P+ZuE9RN+4ELhDZvK5gnDjWtTyEf+a6xURgjDnzJj+kDn/9e5LSY2YjMWHRkxtIOvQ6OvLL3fXSlZk+vktyJXTih1xFf96dCYYfh8HJIny122znANT4ZOxRUndTBZcQH1Qa72yzStTJlSXg99NRFfmFRB8dCupyG4fcOk76nPbhn+Z83+KNkPHSMhTWJB+biz+e3SXMcN1azqhYmdUQBwJuQUwUgtKDbZ3JhTK7LulO+aDblwwlOo5XpRTZeDAaCQTAtLto5PeBp4IS5c1NI5s40IVgjRlkBW/6IssafgCbu73hgc74hB3/6ucf7y7OEl3FoUqaYdwg1yRBDg/er276E7uedS6dZy6jV41Bia8NzQU92HrrxjyF3YDYHAftJJ6/K6STHHItt6h4XgGdwgZIxjwlRmzudCP32WTbAFESDmJ2OQ5ExAyQRoIRjvDijmHt9eiv3W13DfWdk1oAopmxF0F0XzuvmApE2HeTwlZ5o3KS05aarLH0BOxYDE6p9EZ+G/klCq9Y7L+6RLQQntwPZHEyCJFIMevwc0cCgQn97D4XyUyEo/Ns=
  - secure: WnfcDaTQQCcmCXi4Rbk2LfbBg9RsVal4Gz+DWqDXtyMLjSRZMWcJW23XeLOnWaCNgLIKI7u3d4C+KXcB4+3mwni5uRjWzrDCeT2ykIscPUotFQK86DHCxjkLVpRw8lBH7W9fx2q07w7gzx6GBzC42Px3drTSDDR8ZNA+rHh8VHKCLueP68twddSc3WujD6S8Z3JkPI2pjYqXbYosDd/dpN48DhfjN9ifoQCoEaLtm+pA2NC8GFSWaks6GVS13L6m/FOzPfeRBXRE19iMyUw6yc0zm9AXZfnpafJCwmCDade0IvFykLT9T7kDumoYH1B0NcSVzOyqD2a9khlnz8S2yLH55Yh6ZF3enF+OGPctpOKaTS0IIg/VaAXYYcfxEhOTRqz39TU8puwqjrLjOTT9/Ah4Z6LhZEGb6QdUwVY+yo2mD1X43vNYWc8ZQr1E+wEzbsrlneRa2T+TO3LsBvXKzSQRdfNBXSL9sIWnG7D79pM+tFFAJJQ6Xxhw9BZTvHSfqk+GSPaEl7XcF1G39IFAisifHYQEaO5IJ2pX+9Zac8tPqUk3EXJH4gcgY7sBXGEZ6C3fdg7j3lGEc6SyW3eVViWO45gZq0I+uU10FTg2SDYjOyjWtS9MC18FfW4p1pyEhkk+PkpWl8wmY7mAFrzoVwOuZaSctTbYnAtAU8MsgT8=
